### PR TITLE
adding thumbnail with the license logo

### PR DESCRIPTION
**Pull request by ghost**
**This PR does basically aim at:**
- *adding a logo of the mozilla foundation/public license to the document;*

---

**the main motivation behind such a thing is basically to:**
- *help improving the overall look of the file;*
- *documenting licensing;*
- *helping SEO the file;*

### CODE REVIEW

**Comment by MichaelKohler** [comment]
Thanks for the idea! Please note that https://github.com/mozilla/fx-webcompat-campaign/blob/master/LICENSE uses MIT, not MPL. Therefore we should not put on the MPL screenshot you have there. What we could do though is using this badge here: https://gist.github.com/lukas-h/2a5d00690736b4c3a7ba#the-mit-license . These badges are usually put on top of the file. See https://github.com/mozilla/send for example.

**Review by MichaelKohler — CHANGES_REQUESTED** [review]
see comment above

**Comment by ghost** [comment]
**previous commit does basically aim at:**
- *removing mozilla public license logo;*
- *adding mozilla logo;*
- *adding mit license license logo;*

---

**the main reason for that does basically lie within:**
- *the fact i previously added a wrong license type;*
- *it was suggested to add the proper one;*

---

**furthermore:**

- *i took as an advantage to also add the original logo;*

**Review by MichaelKohler — APPROVED** [review]

**Comment by MichaelKohler** [comment]
Thanks!

**Pull request merged**
