### PR TITLE
reviewing code of conduct rhetorically-wise

### PR DESCRIPTION
**Pull request by ghost**
**this PR does basically aim at:**
- *reviewing code of conduct rhetorically-wise;*
- *by doing so, making it more clear and easier to read;*

### CODE REVIEW

**Review by MichaelKohler — CHANGES_REQUESTED** [review]
Re-reading this again, I think we can get rid of the "How to treat each other" part. This is fully covered by the Particiaption Guidelines. Could you please remove that part?

I agree on the addition of the "political views".

**Comment by MichaelKohler** [comment]
Thanks a lot for your efforts :)

**Comment by ghost** [comment]
DONE!!!

**Comment by MichaelKohler** [comment]
I think GitHub inline editing has some bugs. Looking at the diff of your last commit, I only see that the indentation changed, but the content is still there. Could you please double check?

https://github.com/mozilla/fx-webcompat-campaign/pull/31/commits/d0091c70729c68ff584da082c20206c4720085dc

**Comment by MichaelKohler** [comment]
BTW, you can see the final diff against the current website status here: https://github.com/mozilla/fx-webcompat-campaign/pull/31/files

Nice move adding the separators there as well! It will be nicely consistent through all files.

**Comment by ghost** [comment]
I already know that one. and if you add .diff to the end of the link you see the whole metadata of the PR

**Comment by MichaelKohler** [comment]
I'm closing this PR as this project is done and I'm putting this repository into read-only mode.

**Pull request closed without merging**
