### PR TITLE
improving rethorics of contribution policy file

### PR DESCRIPTION
**Pull request by ghost**
**this PR does basically aim at:**

- *improving the overall way as this file is written;*

---

**my goal with this PR was basically to:**

- *improve the experience of reading the file, by slickly improving the way as it is written;*

### CODE REVIEW

**Review by MichaelKohler — CHANGES_REQUESTED** [review]
As I've already merged your other one, would you mind rebasing this one on top of the current master? Otherwise we'll lose the separators again.

Thanks!

**Comment by ghost** [comment]
hey michael how can I do the rebase on of my current master?

**Comment by MichaelKohler** [comment]
> hey michael how can I do the rebase on of my current master?

are you using the GitHub web interface? In that case, I think the easiest way for this is to click on edit again as it's not that much of changes. There might be another way, but I'd not be aware of that.

If that's too much work for you, I can do it on the command line here.

**Comment by ghost** [comment]
I am using the web interface. but i can also use the desktop and the GNU bash command line

**Comment by MichaelKohler** [comment]
> I am using the web interface. but i can also use the desktop and the GNU bash command line

On the command line it would be:
```
$ git clone git@github.com:tiagmoraismorgado/fx-webcompat-campaign.git
$ cd fx-webcompat-campaign
$ git checkout patch-2
$ git rebase master
# This takes the current master branch and applies your last commits on top of that again
# This means that you might end up with a conflict, but shouldn't be the case here
$ git push -f origin patch-2 # as the repository history is rewritten through the rebase, it needs -f
```

**Comment by MichaelKohler** [comment]
This is manually merged by https://github.com/mozilla/fx-webcompat-campaign/commit/d8042fe09187c6e71f0902147a6c2d07433fe371

**Pull request closed without merging**
